### ISSUE TITLE
CiteUlike and Ciao datasets

### ISSUE THREAD

**Issue by chenchongthu** [donalee/BUIR#1]
Would you please share the CiteUlike and Ciao datasets used in your paper? Thanks!

**Comment by donalee** [comment]
You can download the datasets from the following links:
`CiteULike` : https://github.com/changun/CollMetric/tree/master/citeulike-t
`Ciao` : https://github.com/CQU-CSE/DatasetCollection
Thanks!

**Comment by chenchongthu** [comment]
Thanks for your reply! Actually I want to reproduce the results reported in your paper. So would you please upload the datasets that exactly the same as those used in your paper? Or would you upload the data preprocessing code?

**Comment by donalee** [comment]
The data preprocessing code (e.g., filter_interactions) is already included in the `Utils/data_utils.py`. In my experiments, I used the raw data (in the same format with `user.dat` of the toy-dataset), and filtered long-tail users and items on-the-fly while loading each dataset from the raw file. Thanks!

**Comment by chenchongthu** [comment]
Thanks!

**Comment by Wjk666** [comment]
May I ask you about the detailed parameters in the operation of filtering? Take the dataset Ciao as example, the number of users and items (https://github.com/CQU-CSE/DatasetCollection) is more than that reported in your paper table 1.
Thanks a lot!

**Comment by Coder-Yu** [comment]
> Thanks for your reply! Actually I want to reproduce the results reported in your paper. So would you please upload the datasets that exactly the same as those used in your paper? Or would you upload the data preprocessing code?

Hi Chong,
Have you successfully reproduced the results? I have read the official codes and re-implemented the method with Tensorflow. However, the performance is much lower than the reported. I conducted experiments on some datasets with long-tail users and items, and the results were a bit disappointing.
